### ISSUE TITLE
Avoid Parsing

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMakeTest#10]
Right now CMakeTest parses the file. Similar to how member functions are implemented in CMakePPCore, I think it's possible to do something like:

```cmake
ct_add_test(my_test)                               #Line 1
function("${my_test}")                             #Line 2 
                                                   #Line 3
    ct_add_section("${my_test}" a_section)         #Line 4
    function("${a_section}")                       #Line 5
                                                   #Line 6
       ct_add_section("${a_section}" a_subsection) #Line 7
       function("${a_subsection}")                 #Line 8
                                                   #Line 9
       endfunction(a_subsection)                   #Line 10
       ct_end_section()                            #Line 11
                                                   #Line 12
    endfunction()                                  #Line 13 
    ct_end_section()                               #Line 14
                                                   #Line 15
endfunction()                                      #Line 16
end_test()                                         #Line 17
```

This works by:
1. `add_test` creates a unique function name (call it `test1`) and assigns it to `my_test`
2. CMake records the definition of `test1` (lines 2-16)
3. Execution continues on line 17
4. `end_test` on line calls `test1`
5. `test1` runs starting on line 3
6. Execution continues until `add_section` on line 4
7. `add_section` on line 4 determines a new function name call, it `test1.1`
8. The user's definition of `test1.1` (lines 5-13) is recorded by CMake
9. `end_section` on line 14, runs `test1.1`
10. execution returns to line 6 (still in the scope of `test1` up to that point)
11. `test1.1` continues until line 7 where, a new function name is made, say `test1.1.1`
12. CMake records the definition of `test1.1.1` (lines 8-10)
13. Execution continues on line 11
14. `end_section` on line 11 calls `test1.1.1`
15. `test1.1.1` runs starting from line 9 (still in the scope of `test1` and `test1.1`)
16. `test1.1.1` completes returning control to `end_section` on line 11
17. `end_section` on line 11 cleans up `test1.1.1` and `test1.1` continues
18. `test1.1` gets to line 13 and control returns to `end_section` on line 14
19. `end_section` on line 14 cleans up `test1.1`
20. `test1` continues on line 15
21. `test1` completes on line 16 returning control to `end_test` on line 17
22. `end_test` cleans up

The only hiccup I foresee is running tests that should fail. Say `test1.1` should fail (and it does). Then when `test1.1` fails it unravels the entire stack. The only way to prevent this is to run tests that should fail in sub calls (`end_section` on line 14 runs `test1.1` as a subcall).

**Comment by ryanmrichard** [comment]
Another hiccup is how to keep all of the above running in clean directories.

It also now occurs to me that the semantics of the test are also different than how they are now. Presently, each subtest starts from the add_test fence and runs until the just-encountered end fence. The above would not "unwind" the stack all the way, it just wouldn't contaminate namespaces. This may be a deal breaker as it means the individual tests can influence each other.

**Comment by ryanmrichard** [comment]
Believe I have figured out how to get around the "unwind" problem. If we make each `ct_add_section` command simply return when a flag is set, then we could just keep calling `my_test`, setting flags to "unwind" the stack. Consider a much simpler example:

```
ct_add_test(my_test)
function("${my_test}")
    ct_add_section(section)
    function("${section}")
    end_function()
    
    section()
end_function()   

my_test()
```
(where we dropped the `end_test`/`end_section` in favor of just calling the resulting function). Up to some scope issues (which could be minimally resolved with global variables) `section` could be implemented something like:
```
function(section)
    if(${my_test_section_done})
        return()
   endif()
   set(my_test_section_done TRUE)
endfunction()
```

**Comment by AutonomicPerfectionist** [comment]
Just some brainstorming here, I'm thinking of having `add_test` append the name of the test to a list (depending on whether that test has been activated for this run or not), and then have the main function (something like `run_tests`) generate new, temporary files that `include` the main source file and call the functions. Then it could run each file/test in a separate process and in complete isolation (minus the cache, not sure how to deal with that, maybe run in separate build directories so caches aren't shared?). This would require top level tests be entirely self-contained, meaning things like`include` would have to be used inside the function to be executed properly, but luckily it seems as if CMake allows this. Do you know of anything that would cause issues with this method?

**Comment by ryanmrichard** [comment]
Running in separate build directories is probably the way to go. In addition to avoiding cache issues it also makes sure that you don't accidentally find assets (libraries, binaries, generated files, etc.) from previous tests. 

I'd hold of on separate processes for now though. Assuming a testing setup like we have in the CMakePPCore or CMaize, unit tests are grouped into files and each file is separately registered with CTest. CTest has the native ability to run each file as a separate process. We thus can piggyback on its parallel capabilities. I also don't see how you could split the function calls into separate processes without parsing and system calls. Separate processes/parsing is more-or-less what CMakeTest currently does and is likely why it is so slow. It should be possible to isolate the parts of a unit test by changing variables.
