### ISSUE TITLE
[BUG] Invalid mangled folder names on Windows

### ISSUE THREAD

**Issue by yobeonline** [CMakePP/CMakeTest#101]
**Describe the bug**
While building my project on Windows, I have the following error message:
```
CMake Error: Could not open file for write in copy operation K:/Gitlab/add_target/build/_deps/cmake_test-build/tests/tests/K:_Gitlab_add_target_build__deps_cmake_test-src_tests_cmake_test/add_section.cmake/src/CMakeLists.txt.tmp
CMake Error: : System Error: Invalid argument
CMake Error at build/_deps/cmake_test-src/cmake/cmake_test/add_dir.cmake:53 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  build/_deps/cmake_test-src/tests/CMakeLists.txt:15 (ct_add_dir)
```
The problem comes from the generated mangled path "K:/Gitlab/add_target/build/_deps/cmake_test-build/tests/tests/K:_Gitlab_add_target_build__deps_cmake_test-src_tests_cmake_test/add_section.cmake/src/CMakeLists.txt.tmp" which  failed at removing the colon which is forbidden. (see [here](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names))

**To Reproduce**
You can try the project I am trying to test with cmake-test, on Windows:
```
git clone https://github.com/yobeonline/add_target.git --branch cmake-test
cmake -B build -S add_target
```

**Comment by ryanmrichard** [comment]
@zachcran you run Windows right? Any chance you can take a look at this? If you can find the source of the problem I think you just need to call [`cmake_path(APPEND`](https://cmake.org/cmake/help/latest/command/cmake_path.html) to properly merge the paths.

**Comment by zachcran** [comment]
Sure, I'll see what I can do in the next couple days. I'm sure my development environment in my Windows distro isn't up to date anymore since I haven't worked with CMake or CMaize in a while, so it will take me a bit to get that set up again.

**Comment by yobeonline** [comment]
I believe one instance of the problem is [here](https://github.com/CMakePP/CMakeTest/blob/master/cmake/cmake_test/add_dir.cmake#L50) where directory separators are replaced with underscores, leaving out erroneous colons on Windows.

Hope it helps.

I should be able to spend some time on the problem next week I you wish.

**Comment by zachcran** [comment]
@yobeonline Let us know if this fix works for you and if you find any other issues! It seemed to work in my testing with your project.

**Comment by yobeonline** [comment]
@zachcran I confirm the problem is fixed in v0.1.15. Thank you for the fast work. I appreciate it!

**Comment by zachcran** [comment]
@yobeonline If you have the time, please open an issue on it. I also saw those errors, and am seeing them on Linux too with a simple test project. From what I can tell with brief testing, the CMakePPLang dependency is not being propagated properly, but I am not sure why yet. I'll keep digging over the next few days, but I don't have much time today to do more.

**Comment by zachcran** [comment]
@yobeonline Also, based on what I understand of your project, consider checking out [CMaize](https://github.com/CMakePP/CMaize) ([documentation](https://cmakepp.github.io/CMaize/)) if you haven't already! It might fit your needs for a less verbose interface to writing CMake build systems (and is also provided by us).

**Comment by ryanmrichard** [comment]
Just to follow up on @zachcran comment. CMaize may be of interest; however we've done very limited Windows testing with it. That said, we want to support Windows, I'm just warning it might still be buggy.
