### ISSUE TITLE
Is there a way to get access to function vars ?

### ISSUE THREAD

**Issue by dschiller** [CMakePP/CMakeTest#23]
Is there a way to get access to function vars without PARENT_SCOPE ?

**Comment by ryanmrichard** [comment]
If I'm understanding you correctly you want to do something like:

```.cmake
ct_add_test(NAME "my_test")
function(${my_test})

    ct_add_section(NAME "a_section")
    function(${a_section})
        set(a_variable "Hello World!!!")
    end_function()

    # a_variable is empty in this scope so should print
    # "a_variable = "
    message("a_variable = ${a_variable}")
end_function()
```
and have it print "a_variable = Hello World!!!". If so, I think if you do (note the use of `macro` instead of `function`):

```.cmake
ct_add_test(NAME "my_test")
function(${my_test})

    ct_add_section(NAME "a_section")
    macro(${a_section})
        set(a_variable "Hello World!!!")
    end_macro()

    message("a_variable = ${a_variable}")
end_function()
```
The `ct_add_section` won't be run in a new scope and your variables will be available outside of the section. 

If this isn't what you are looking for can you post an example?

**Comment by dschiller** [comment]
Hey Ryan, exactly. I figured out that running macros works fine and their vars are accessible from the test.

Say I use this function I want to test:

### my-function.cmake
```cmake
function(do_something arg1 arg2)
   set(DOSOMETHINGVAR "itsvalue is ${arg1}")
endfunction()
```

And in my test I want to access it:

### test-my-function.cmake
```cmake
ct_add_test(NAME test_my_function)
function(${test_my_function})

   include(my-function.cmake)

   ct_add_section(NAME test_DOSOMETHINGVAR_is_ARG1)
   function(${test_DOSOMETHINGVAR_is_ARG1})
      do_something("value a" "value b")
      ct_assert_equal(DOSOMETHINGVAR "itsvalue is value a")
   endfunction()

endfunction()
```

**Comment by ryanmrichard** [comment]
@dschiller unfortunately the scope rules for functions vs. macros are set by CMake itself, not CMakeTest. See [here](https://cmake.org/cmake/help/latest/command/macro.html#macro-vs-function) for more details. I don't think that it is possible to do what you want without modifying `do_something` to either: make it a macro, have it set the value in the parent scope, or put the variable in the CMake cache.

**Comment by dschiller** [comment]
Thanks Ryan, I expected that but wanted to be sure. Thanks again!
