### ISSUE TITLE
Unit Test Examples

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMakeTest#31]
As brought up by #25, the examples in the documentation are currently not being unit tested and thus can fall out of sync with the code base. We should ensure that code snippets in the documentation are unit tested. One way to possibly do this for the README is to switch it to reST from markdown (and then use literal includes)

**Comment by AutonomicPerfectionist** [comment]
As discussed in #57, the README does not allow literal includes on Github for security reasons. However, the rest of the documentation was updated to use tested examples.

Fixed by #57
