### ISSUE TITLE
Is there a way to access generated build files inside a test ?

### ISSUE THREAD

**Issue by dschiller** [CMakePP/CMakeTest#32]
When I execute my tests the build files will be generated after tests run.

```
        test......................................................................................................PASSED
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/dirk.schiller/Work/Coding/CPP/cmake-tools-tests/build
```

Is it somehow possible to access those files inside the tests ?

**Comment by ryanmrichard** [comment]
I don't see any reason why you wouldn't be able to access the files. 

That said, exactly how to best do it depends on exactly what you're trying to do. Assuming the files you are trying to access are being created by the `cmake` invocation which is driving the test, you should be able to use the standard CMake build directory variables like `CMAKE_BINARY_DIR` to get the build directory. If the files were written by a prior invocation of the `cmake` command, then you'll need to pass the path to the test (or hard-code it, which is unlikely to be portable). Either way, once you have the path you should then be able to use CMake's `file` command to parse it.

@AutonomicPerfectionist maybe I'm missing it, but is there a way to pass variables to the `ct_add_dir` command? If not it could be useful, something like:

```.cmake
# Adds the tests in this directory
# Each test will see the global variable "My_Variable" set to "my_value"
ct_add_dir("." CMAKE_ARGS -DMy_Variable=my_value)
```
The tricky part, would be dealing with lists (both of variables and of variables set to lists) and ensuring they get forwarded correctly.

**Comment by dschiller** [comment]
I want to access a file inside the `build` folder and I think this folder is created after the tests. At least with `ct_assert_file_exists(build/CMakeFiles/NIT.dir/build.make)` I get an error:

```
CMake Error at CMakeTest/cmake_test/overrides.cmake:44 (_message):
  Testing forcibly stopped, no further tests will be executed.
  Details: Unexpected exception caught while executing test
  "test_target_NIT_has_custom_command_for_POST_BUILD_with_proper_Key_and_Id".
  Type: GENERIC_ERROR, Details: File does not exist at
  build/CMakeFiles/NIT.dir/build.make.
```

**Comment by ryanmrichard** [comment]
It's probably tangential to the actual issue, but I recommend always using full paths; it's not always immediately apparent what directory CMake thinks it is actually in.

Without more detail regarding your use case, I am not sure how to help. If the folder is created after the test runs, I don't understand how the test could be expected to use it. You have to generate the files first and then test them. Are you looking for a way to ensure the order the tests run in?

**Comment by dschiller** [comment]
Thanks Ryan! I think I then need to run a second test session. One test invoke the creation of this file and afterwards in a second session I could parse the created files.

**Comment by AutonomicPerfectionist** [comment]
> @AutonomicPerfectionist maybe I'm missing it, but is there a way to pass variables to the `ct_add_dir` command? If not it could be useful, something like:
> 
> ```cmake
> # Adds the tests in this directory
> # Each test will see the global variable "My_Variable" set to "my_value"
> ct_add_dir("." CMAKE_ARGS -DMy_Variable=my_value)
> ```

@ryanmrichard no there is currently not a way to do so, and from what I can tell adding such functionality would be difficult. Evidently `ctest` treats the `-D` switch differently than the normal `cmake` command. Documentation is sparse but it appears to share two different arguments with the `-D` shortened switch, the "usual" one and a shortened form of `--dashboard`. Additionally, the usual form of  `-D` appears to only set a variable when run in script mode, which we can't do. Since `ctest` has its own internal `cmake` command it uses I don't see a way to bypass `ctest`'s admittedly poor CLI design.

**Comment by ryanmrichard** [comment]
@AutonomicPerfectionist do you recall if there was a reason that https://github.com/CMakePP/CMakeTest/blob/master/cmake_test/add_dir.cmake#L25 uses `ctest` and not `cmake`? Only thing I can think of is it's for the convenience of being able to run the whole build process (configure, build, test, install) as a single command.  

When a user tests a repo they run `ctest`, which then runs the commands which are registered in the `add_test` commands sprinkled throughout the project. As we have it setup, `ctest` is going to call itself to run the test. This seems redundant to me.

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard I think that was left over from when I was initially deciding on a design, I just made a quick change over to the `cmake` command and everything works just fine. Apologies, I was looking at it during the night and that thought never occurred to me. I'll get started on adding that in a new branch.
