### ISSUE TITLE
Add setup and teardown functionality similar to JUnit and Python's unittest library

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [CMakePP/CMakeTest#37]
**Is your feature request related to a problem? Please describe.**
Currently CMakeTest has no way to register `setup()` and `teardown()` functions. They are not necessarily required as they can be implemented with regular functions and called manually inside each test, but it would be helpful for test-writers to have this functionality baked into CMakeTest.

**Describe the solution you'd like**
Currently properties of tests and sections are stored in CMakePP global variables, keyed by the test unique identifier. We should be able to add additional global variables to store IDs of `setup()` and `teardown()` functions fairly easily. A helper function called `ct_register_setup()` or similar would then handle the muscle of updating these global variables, the first parameter would have to be a test identifier, either the variable name or a dereferenced value would work, e.g. `ct_register_setup(my_test my_setup)` or `ct_register_setup(${my_test} my_setup)`. While both are easy to do, we should probably decide on a consistent format.

**Comment by ryanmrichard** [comment]
CMakeTest is modeled after Catch2 where you don't explicitly need setup/teardown because it's implied by the section scopes. For example:
```
ct_add_test(NAME x)
function(${x})
    # This is set-up for all tests
   
    ct_add_section(NAME y)
    function(${y})
        # This is set-up for test z
 
        ct_add_section(NAME z)
        function(${z})
            # run a test, environment is x + y + z
        endfunction()

        # run a test, environment is x + y
    endfunction()

    # run a test, environment is x
endfunction()
```
IMHO this is easier than the setup/teardown approach as you have the complete test in front of you (as opposed to having to go track down the setup/teardown approaches to see what they're doing. Am I missing something.

**Comment by AutonomicPerfectionist** [comment]
Nope, I've just been using a lot of JUnit for class and thought it might be something to consider implementing.

**Comment by ryanmrichard** [comment]
Was thinking about this some more while working on some C++ tests (where I use Catch2 which works similarly); there I have basic set-up that is common to every `add_test` command and I have factored that setup into an `initialize` function I manually call for each `add_test`. I could see how the same thing could happen with CMake tests (say working out paths for example). So perhaps it's worth exploring a setup/teardown function for the entire runner (some setup that occurs before the contents of a `add_test` command are run)? IIRC, under the hood we do some setup/teardown already to avoid clobbering other tests. So these would be user-defined commands that get run with the predefined ones. Until an actual use case appears I wouldn't worry about this though.
