### ISSUE TITLE
CI Improvements

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMakeTest#45]
CMakeTest has CI for documentation and unit testing. This issue is for adding more administrative CI like:

- [x] Semantic versioning through tagging
- [x] #69

CMinx has the same CI considerations so the solutions can just be taken from CMinx (requires CMakePP/CMinx#47 to be resolved first).

**Comment by zachcran** [comment]
"Semantic versioning through tagging" will be handled by #68 and is covered in issue #64.

**Comment by AutonomicPerfectionist** [comment]
Will this be resolved by #77 or are there more CI Actions we want to add?

**Comment by zachcran** [comment]
I believe this is good to be closed now. @ryanmrichard do you have any other CI Actions to add?
