### ISSUE TITLE
Convert CMakeTest internal test representations to CMakePP objects

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [CMakePP/CMakeTest#47]
**Is your feature request related to a problem? Please describe.**
The internals of CMakeTest currently represent a test and its subsections as a collection of values stored in CMakePP globals. This worked just fine initially but as more and more features are added it is becoming increasingly difficult to maintain. For example, the fix for #22 was initially easy to implement, but once #24 was merged it became much more difficult to implement, due to the need to keep track of which tests and sections have been executed already as well as which sibling and parent sections still need to be executed.

**Describe the solution you'd like**
It would be much easier to add features to and maintain CMakeTest if tests and sections were instead implemented as CMakePP objects with a list of subsection objects, a reference pointing to the parent object, the name of the test or section function it represents, a boolean stating whether the section has been executed already, and any metadata like EXPECTFAIL or print_length.

**Comment by ryanmrichard** [comment]
How much work do you think this would be? Do you have a design in mind already?

**Comment by AutonomicPerfectionist** [comment]
I don't believe it should take longer than a week or two. The way we're doing things now kind of resembles structs anyway, each section's data is stored in a global variable with a name beginning with the "execution unit" it belongs to, so all we'd need to do is factor those variables into a class and have the current execution unit global variable contain a reference to it.

**Comment by ryanmrichard** [comment]
Sounds good to me. Just to clarify, would the user-facing API still be function-based (as opposed to object-oriented)? IMHO a functional API should integrate better into existing CMake setups, since native CMake is functional.

**Comment by AutonomicPerfectionist** [comment]
Yep, this is just proposing a change in internal structures, all user-facing APIs should remain the same
