### ISSUE TITLE
Document How CMakeTest Works

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMakeTest#5]
How CMakeTest is actually implemented is probably not obvious to many people. It should be documented.

**Comment by dschiller** [comment]
Yes it would be nice to see if there are more commands like `ct_assert_equal`.

**Comment by ryanmrichard** [comment]
@dschiller for what it's worth we have [this](https://cmakepp.github.io/CMakeTest/developer/asserts/index.html). That said, we definitely need better examples and more human-readable documentation to complement it though.

**Comment by dschiller** [comment]
Hey Ryan, thats pretty nice! Where is `this` comming from - where do I find the links for it ?

**Comment by dschiller** [comment]
Maybe it's worth to link it in the readme.md in this repository.

**Comment by dschiller** [comment]
I found it, it's on the right side of the repository:

<img width="441" alt="Screenshot 2023-01-03 at 18 21 12" src="https://user-images.githubusercontent.com/3144986/210408634-9d268005-db5b-4946-ac4c-acad077095c9.png">

Maybe a Titile like `Documentation` would help.

**Comment by ryanmrichard** [comment]
@dschiller this is all great feedback! 

We have started to clean this repo up, including the documentation, in preparation for a 1.0 release. At that point, the documentation (and repo setup) should be a lot closer to CMinx's quality. Admittedly this process has been slower than I'd like since @AutonomicPerfectionist is currently splitting time among this repo, CMinx, and school and I'm heavily focused on getting a 1.0 out for the software built on the CMakePP stack (our other CMakePP team member @zachcran is focused on getting a 1.0 of [CMaize](https://github.com/CMakePP/CMaize) out). I think @AutonomicPerfectionist is almost done with the CMinx issues he's been working on, so I'm optimistic that he'll be able to start making some of these changes in the near future.

In the meantime please feel free to continue open issues with any additional questions/comments you have (it's very helpful for letting us know what needs to be added to the documentation and/or what features we missed).

**Comment by dschiller** [comment]
Great to hear about your progress - never complained that as you always work immediately on the issues iI raised, also i nthe other projects. And great to read about CMaize!

**Comment by ryanmrichard** [comment]
@dschiller thanks for your understanding! My last comment was really just a preemptive explanation for why we will probably be a bit slower to work on this issue.

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard @dschiller apologies for not responding earlier; I came down with an illness over the weekend. The reasoning for those parameter names was so they would not conflict with any user code, as functions implicitly inherit all variables from the scope in which they are called. Since we are calling user-defined test functions from our own functions, we have the unique position of ensuring no naming conflicts happen.

For example: say we use a parameter named `file` in one of our functions, and we execute a test that checks for whether a `file` variable has been set by a previous function call. We now are conflicting with the test, and it will incorrectly find a `file` variable has been defined. There might be a CMake policy somewhere to disable the implicit scope inheriting but last I checked I couldn't find one

**Comment by AutonomicPerfectionist** [comment]
Additionally, I was working on the documentation in #50 actually but ran into build issues regarding CMinx, so we need to do a bit of reworking in that regard since CMakeTest is currently using functions from an older version of CMinx that no longer exist

**Comment by AutonomicPerfectionist** [comment]
That would indeed help in this situation, and shouldn't be too hard to implement

**Comment by dschiller** [comment]
You removed the `assert` documentation at https://cmakepp.github.io/CMakeTest/developer/asserts/index.html ?

**Comment by AutonomicPerfectionist** [comment]
That's actually a result of a bug in CMinx, #57 includes a workaround for it though
