### ISSUE TITLE
Is there another Setting needed for showing `Failed` tests in correct print length ?

### ISSUE THREAD

**Issue by dschiller** [CMakePP/CMakeTest#58]
It seems `ct_set_print_length()` doesn't respect failed tests.

![Screenshot 2023-01-12 at 10 08 58](https://user-images.githubusercontent.com/3144986/212026273-bdc805e2-2a96-4a36-b569-7f6002665fcf.png)

<img width="431" alt="Screenshot 2023-01-12 at 10 09 26" src="https://user-images.githubusercontent.com/3144986/212026300-0f956578-4ad0-44c6-9b8d-c2f93ff2f175.png">

**Comment by ryanmrichard** [comment]
This looks like a bug to me. I would have expected the `ct_set_print_length()` to also affect `FAILED`.
