### ISSUE TITLE
Introduce Tags

### ISSUE THREAD

**Issue by dschiller** [CMakePP/CMakeTest#64]
**Is your feature request related to a problem? Please describe.**
You introduced a breaking change with https://github.com/CMakePP/CMakeTest/commit/393a85e774a2c4cb89ac720abe3ab252213bf933

**Describe the solution you'd like**
If you would introduce Tags we do not need to pin to a certain commit, instead we could use tags. Also it seems not to be a good practice to append to `master` instead a specific version is preferred to avoid breaking changes.

**Describe alternatives you've considered**
Alternative would be to pin to a specific commit.

**Additional context**
Our pipeline failed to build as the mentioned commit switched from `get_cpp` to `get_cmaize` which is a breaking change in our pipeline as we do not pull `CMaize` as a dependency.

**Comment by zachcran** [comment]
@ryanmrichard Sure, I can look into why the rename broke things. Things are a bit busy right now, but I should be able to get to it in the next day or two.

**Comment by dschiller** [comment]
For our unit tests we add the Dependency in CMake like

```cmake
# import CMakeTest
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/libs/CMakeTest")
list(APPEND CMAKE_MODULE_PATH "${CMAKE_BINARY_DIR}/_deps/cpp-src/cmake")
list(APPEND CMAKE_MODULE_PATH "${CMAKE_BINARY_DIR}/_deps/cmakepp_lang-src/cmake")
include(cmake/get_cpp)
include(cmake_test/cmake_test)
```
The line `include(cmake/get_cpp)` then made the build fail.

**Comment by zachcran** [comment]
@dschiller Sorry for the delay on this. The aforementioned PR has been merged into CMakePPLang and you can find the example project under `CMakePPLang/examples/cmakepplang_example`. The documentation explaining the example project and walking through making it is [here](https://cmakepp.github.io/CMakePPLang/getting_started/example_project.html). Please open an issue over in CMakePPLang if you have any questions about the tutorial or example!
