### ISSUE TITLE
Function for adding directories of tests to CTest

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMakeTest#7]
Right now you have to manually add each CMake unit test to CTest, which ends up looking like:

```.cmake
add_test(
    NAME <test_name>
    COMMAND ${CMAKE_COMMAND}
            -DCMAKE_MODULE_PATH=<path2modules>
            -P <path/to/file/with/test>
)
```
for each test.

It would be great to have a function `ct_register_cmake_tests(<dir>)` which crawled through a directory (and all subdirectories) and did this automatically. The real trick to implementing this would be getting it to recognize when a new test was added. There also needs to be a mechanism for having it ignore certain tests it finds (because users may not want them to run, or they require special setup, for example).

**Comment by AutonomicPerfectionist** [comment]
Fixed in #13
