### ISSUE TITLE
[Question] Is 'examples/CMakeTest.cmake' complete?

### ISSUE THREAD

**Issue by zachcran** [CMakePP/CMakeTest#75]
**Before opening this issue I:**

- [x] Checked the documentation for answers
- [x] Looked for similar issues
- [ ] Did a quick internet search

**Description**

I am looking through the files in the repo, and `examples/CMakeTest.cmake' does not appear to be a current or functional example. Is it complete, or a leftover file that should be deleted?

**Comment by AutonomicPerfectionist** [comment]
I did a grep for references to that file and only found one reference in the top-level CMakeLists.txt. It looks like it was originally used for testing/example purposes but is no longer accurate. Removing it should be fine
