### ISSUE TITLE
Remove 'bin' directory

### ISSUE THREAD

**Issue by zachcran** [CMakePP/CMakeTest#78]
**Is your feature request related to a problem? Please describe.**
The scripts in the `bin/` directory are obsolete and should be removed as per discussion in #70 .

**Describe the solution you'd like**
The `bin/` directory and its contents should be removed. This is more of a todo for myself or someone else down the road than anything.

**Comment by AutonomicPerfectionist** [comment]
Yeah those scripts are very old, from the original prototype of CMakeTest I believe. None really do anything for us anymore so I'll remove them next week
