### ISSUE TITLE
[BUG] Potential performance problems with EXPECTFAIL sections

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [CMakePP/CMakeTest#82]
**Describe the bug**
While running tests for CMakePP/CMakePPLang I noticed that EXPECTFAIL tests are significantly slower than regular tests/sections. It is expected to be slower due to the subprocess method of execution, but I'm seeing easily an order of magnitude longer execution times.

**Comment by AutonomicPerfectionist** [comment]
I've found what's going on. It's only an issue specifically for the CMakePPLang test suite because it sets DEBUG_MODE on, which forces many sanity checks like signature checks. Since CMakeTest uses CMakePPLang internally, this also forces CMakeTest code to use those same checks, which causes abysmal performance for all tests setting `DEBUG_MODE`. The `EXPECTFAIL` test performance is more noticeable because they re-run the direct parents of the section, so if all of the tests and sections have significantly worse performance, then that penalty will be multiplied for the `EXPECTFAIL` case.

Personally, I don't really see a workaround, but it also isn't a huge problem. @ryanmrichard any thoughts on this?

**Comment by ryanmrichard** [comment]
Can you turn `DEBUG_MODE` off for `EXPECTFAIL`? Unless someone is trying to verify that `DEBUG_MODE` works correctly, the test is presumably supposed to fail for a reason other than what `DEBUG_MODE` would catch.

**Comment by AutonomicPerfectionist** [comment]
A common test case I see is ensuring signature verification fails on incorrect types, which is one of the checks affected by DEBUG_MODE. An example test I saw in CMakePPLang:

```cmake
ct_add_section(NAME "arg_must_be_desc" EXPECTFAIL)
function("${arg_must_be_desc}")
    cpp_contains(TRUE an_item a_list)
endfunction()
```

The `cpp_contains()` call here only fails if `CMAKEPP_LANG_DEBUG_MODE` is on, as is set in the parent test.

One thing we can do is revert DEBUG_MODE to false inside CMakeTest code and restore it upon executing the test code. However, that means we can't use it for verifying CMakeTest code. A way to fix that issue would be to have an option`CMAKETEST_DEBUG_MODE` that we would set `CMAKEPP_LANG_DEBUG_MODE` to instead of false.

**Comment by ryanmrichard** [comment]
What's the difference in execution time with `DEBUG_MODE` on vs. off? This probably isn't worth worrying about right now unless it's significantly different.

**Comment by AutonomicPerfectionist** [comment]
With a single test and a single EXPECTFAIL section as follows:
```cmake
ct_add_test(NAME test_same_name_diff_dir)
function(${test_same_name_diff_dir})
        #set(CMAKEPP_LANG_DEBUG_MODE TRUE)

        ct_add_section(NAME test_section EXPECTFAIL)
        function(${test_section})
                message(FATAL_ERROR test)
        endfunction()
endfunction()

```

Without debug mode I get:
```
real	0m0.400s
user	0m0.340s
sys	0m0.056s
```

With debug mode I get:
```
real	0m2.203s
user	0m2.115s
sys	0m0.082s
```

The penalty compounds as the section depth increases

**Comment by ryanmrichard** [comment]
Based on these timings I think it's worth addressing (when you get a chance, no rush).
