### ISSUE TITLE
Error if nesting add_test

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMakeTest#9]
The intent is to copy Catch2's unit testing model and have `cpp_add_test` be the outermost level of a test case. All sections within that test case should be fenced off with `cpp_add_section`. Right now if you accidentally nest `cpp_add_test` sections you do not get an error, but rather wipe out all parent scope. CMakeTest should detect nested `cpp_add_test` sections and raise an error.

**Comment by ryanmrichard** [comment]
@AutonomicPerfectionist will this still be an issue with #13?

**Comment by AutonomicPerfectionist** [comment]
Should be fixed now in #13, nesting ct_add_test() is undefined behavior so instead of simply throwing an exception and continuing the interpreter is forcibly stopped with an appropriate error message.
